### ISSUE TITLE
Update to bootstrap icons v1.7

### ISSUE THREAD

**Issue by domesticmouse** [ricardodalarme/Bootstrap-Icons-Flutter#1]
I'm curious what the process is to update to version 1.7 of the bootstrap icons font?

**Comment by ricardodalarme** [comment]
It's simple, I'll update it this weekend! And I'll add a process to automate upcoming releases (:

**Comment by domesticmouse** [comment]
Thank you!

**Comment by ricardodalarme** [comment]
Released! (:
